{
   "about_app": {
      "description": "The title for the About App feature",
      "message": "アプリについて"
   },
   "about_version_num": {
      "description": "The version number of the application",
      "message": "バージョン番号: "
   },
   "appname": {
      "description": "Title of the Chrome App name. [CHAR LIMIT=44]",
      "message": "Chrome 接続診断"
   },
   "appname_beta": {
      "description": "Title of the Chrome App name (Beta). [CHAR LIMIT=44]",
      "message": "Chrome 接続診断（ベータ版）"
   },
   "appname_dev": {
      "description": "Title of the Chrome App name (Dev). [CHAR LIMIT=44]",
      "message": "Chrome 接続診断（Dev）"
   },
   "apptitle": {
      "description": "HTML and header page title.",
      "message": "接続診断"
   },
   "apptitle_ucase": {
      "description": "HTML and header page title.",
      "message": "接続診断"
   },
   "aria_label_close": {
      "description": "ARIA label for the close button.",
      "message": "閉じる"
   },
   "aria_label_maximize": {
      "description": "ARIA label for the maximize button.",
      "message": "最大化"
   },
   "aria_label_restore": {
      "description": "ARIA label for the restore button.",
      "message": "復元"
   },
   "aria_label_settings": {
      "description": "ARIA label for the settings button.",
      "message": "設定"
   },
   "captiveportalhttptest_log_http_response": {
      "description": "Logger record for full HTTP response length",
      "message": "レスポンス番号/HTTP レスポンス ヘッダー: "
   },
   "captiveportalhttptest_log_network_error": {
      "description": "Logger record for when TCP connection breaks an HTTP request",
      "message": "エラーが発生しました。リクエスト #/エラーのステータス: "
   },
   "captiveportalhttptest_log_response_code": {
      "description": "Logger record for full HTTP response length",
      "message": "レスポンス番号/HTTP レスポンス コード: "
   },
   "captiveportalhttptest_log_response_length": {
      "description": "Logger record for when TCP connection breaks an HTTP request",
      "message": "リクエスト番号/レスポンスの全長: "
   },
   "captiveportalhttptest_name": {
      "description": "Name for the Captive Portal HTTP test",
      "message": "HTTP キャプティブ ポータル テスト"
   },
   "captiveportalhttptest_no_problem_threshold": {
      "description": "Log record for the criteria under which the Captive Portal HTTP request returns a no problem verdict",
      "message": "すべての HTTP リクエストで 204 HTTP ステータス コードが返された場合、HTTP キャプティブ ポータル テストで問題なしという結果が返されます"
   },
   "captiveportalhttptest_noproblem_subtitle": {
      "description": "Title for when a potential problem is found with the HTTP captive portal test.",
      "message": "キャプティブ ポータルは見つかりませんでした。キャプティブ ポータルは、インターネットを自由に閲覧するアクセス権を得る前に、ネットワークのユーザーが表示し操作する必要のあるウェブサイトです。"
   },
   "captiveportalhttptest_noproblem_title": {
      "description": "Title for when no problem is found with the HTTP captive portal test.",
      "message": "インターネット トラフィックはキャプティブ ポータル（HTTP）によってブロックされていません"
   },
   "captiveportalhttptest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the HTTP captive portal test.",
      "message": "キャプティブ ポータルは、インターネットを自由に閲覧するアクセス権を得る前に、ネットワークのユーザーが表示し操作する必要のあるウェブサイトです。ご利用のネットワークでキャプティブ ポータルが見つかりました。インターネットへの無制限のアクセスはブロックされています。"
   },
   "captiveportalhttptest_problem_threshold": {
      "description": "Log record for the criteria under which the Captive Portal HTTP request returns a problem verdict",
      "message": "204 HTTP ステータス コードを返さない HTTP リクエストがあった場合は、HTTP キャプティブ ポータル テストで問題ありという結果が表示されます"
   },
   "captiveportalhttptest_problem_title": {
      "description": "Title for when a problem is found with the HTTP captive portal test.",
      "message": "インターネット トラフィックはキャプティブ ポータル（HTTP）によってブロックされています"
   },
   "chromeinternetdisconnectedtest_log_connection_beginning": {
      "description": "Logger record for when a TCP connection to a specific host and port is about to begin",
      "message": "TCP 接続を試行します。#/ホスト名/ポート: "
   },
   "chromeinternetdisconnectedtest_log_connection_status_known": {
      "description": "Logger record for when a TCP connection status code is known in the Chrome internet connection test.",
      "message": "Chrome のインターネット接続テストで次の TCP ステータス コードが返されました: "
   },
   "chromeinternetdisconnectedtest_name": {
      "description": "Name for the Chrome Internet Disconnected test",
      "message": "Chrome インターネット接続テスト"
   },
   "chromeinternetdisconnectedtest_no_problem_threshold": {
      "description": "Logger record for percent of TCP sockets that return internet disconnected in order for test to fail",
      "message": "インターネット非接続ステータス コードを返す TCP ソケットの割合（下回ったとき、問題なしという結果を表示）: "
   },
   "chromeinternetdisconnectedtest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the Chrome internet connection.",
      "message": "Chrome ブラウザでインターネット接続を使用できます。"
   },
   "chromeinternetdisconnectedtest_noproblem_title": {
      "description": "Title for when no problem is found with the Chrome internet connection.",
      "message": "インターネット接続を使用できます"
   },
   "chromeinternetdisconnectedtest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the Chrome internet connection.",
      "message": "Chrome はネットワークに接続していません。オペレーティング システムのネットワーク設定をご確認ください。"
   },
   "chromeinternetdisconnectedtest_problem_threshold": {
      "description": "Logger record for percent of TCP sockets that return internet disconnected in order for test to fail",
      "message": "インターネット非接続ステータス コードを返す TCP ソケットの割合（等しいか上回ったとき、問題ありという結果を表示）: "
   },
   "chromeinternetdisconnectedtest_problem_title": {
      "description": "Title for when a problem is found with the Chrome internet connection.",
      "message": "ネットワークに接続していません"
   },
   "chromeosinternetdisconnectedtest_log_available_networks": {
      "description": "Logger record for how many networks chrome.networkingPrivate found.",
      "message": "検出された使用可能なネットワークの数: "
   },
   "chromeosinternetdisconnectedtest_name": {
      "description": "Name for the ChromeOS Internet Disconnected test",
      "message": "Chrome OS インターネット接続テスト"
   },
   "chromeosinternetdisconnectedtest_no_problem_threshold": {
      "description": "Condition under which the ChromeOS internet disconnected test returns a no problem result",
      "message": "接続しているネットワーク インターフェースが接続ステータス コードを返した場合は、問題なしという結果が表示されます"
   },
   "chromeosinternetdisconnectedtest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the ChromeOS internet connection.",
      "message": "インターネット接続を使用できます。"
   },
   "chromeosinternetdisconnectedtest_noproblem_title": {
      "description": "Title for when no problem is found with the ChromeOS internet connection.",
      "message": "インターネット接続を使用できます"
   },
   "chromeosinternetdisconnectedtest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the ChromeOS internet connection.",
      "message": "この Chromebook はネットワークに接続していません。ステータス トレイから使用可能なネットワークに接続してください。"
   },
   "chromeosinternetdisconnectedtest_problem_threshold": {
      "description": "Condition under which the ChromeOS internet disconnected test returns a problem result",
      "message": "接続しているネットワーク インターフェースが次の非接続ステータス コードを返した場合は、問題ありという結果が表示されます: "
   },
   "chromeosinternetdisconnectedtest_problem_title": {
      "description": "Title for when a problem is found with the ChromeOS internet connection.",
      "message": "ネットワークに接続していません"
   },
   "chromeossignalstrengthtest_log_signal_strength": {
      "description": "Logger record for the signal strength of a ChromeOS NIC connection",
      "message": "ネットワーク信号名/信号強度: "
   },
   "chromeossignalstrengthtest_name": {
      "description": "Name for the ChromeOS Signal Strength test",
      "message": "Chrome OS の Wi-Fi 信号強度テスト"
   },
   "chromeossignalstrengthtest_no_problem_strength": {
      "description": "Logger record for signal strength for which we render a no problem verdict.",
      "message": "Chrome OS の信号強度のベンチマーク（上回ったとき、問題なしという結果を表示）: "
   },
   "chromeossignalstrengthtest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found in the ChromeOS signal strength",
      "message": "Wi-Fi ネットワークの信号強度は「強い」です。"
   },
   "chromeossignalstrengthtest_noproblem_title": {
      "description": "Title for when no problem is found in the ChromeOS signal strength",
      "message": "ネットワークの信号強度は「強い」"
   },
   "chromeossignalstrengthtest_problem_strength": {
      "description": "Logger record for signal strength for which we render a problem verdict.",
      "message": "Chrome OS の信号強度のベンチマーク（下回ったとき、問題ありという結果を表示）:"
   },
   "chromeossignalstrengthtest_problem_subtitle": {
      "description": "Subtitle for when a problem is found in the ChromeOS signal strength",
      "message": "Wi-Fi ネットワークの信号強度は「弱い」です。"
   },
   "chromeossignalstrengthtest_problem_title": {
      "description": "Title for when a problem is found in the ChromeOS signal strength",
      "message": "ネットワークの信号強度は「弱い」"
   },
   "chromeosversiontest_full_platform": {
      "description": "Full ChromeOS platform number parsed from the HTTP user-agent string",
      "message": "Chrome OS のプラットフォーム番号（完全）: "
   },
   "chromeosversiontest_name": {
      "description": "Name for the ChromeOS Version test",
      "message": "Chrome OS のバージョン名"
   },
   "chromeosversiontest_no_problem_version": {
      "description": "Logger record for ChromeOS platform number for which we render a no problem verdict.",
      "message": "Chrome OS のプラットフォーム番号のしきい値（等しいか上回ったとき、問題なしという結果を表示）: "
   },
   "chromeosversiontest_noproblem_record_log": {
      "description": "Log record for recording that no problem existed with the ChromeOS version.",
      "message": "Chrome OS のバージョン テストで問題は検出されませんでした。Chrome OS のバージョンは最新です。現在の最小バージョン: "
   },
   "chromeosversiontest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the ChromeOS version.",
      "message": "ご使用の Chrome OS は最新バージョンです。接続に関する既知のバグはすべて修正されています。"
   },
   "chromeosversiontest_noproblem_title": {
      "description": "Title for when no problem is found with the ChromeOS version.",
      "message": "Chrome OS は最新です"
   },
   "chromeosversiontest_problem_record_log": {
      "description": "Log record for recording that a problem existed with the ChromeOS version.",
      "message": "Chrome OS のバージョン テストで問題が検出されました。Chrome OS のバージョンが最新ではありません。現在の最小バージョン: "
   },
   "chromeosversiontest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the ChromeOS version.",
      "message": "ご使用の Chrome OS は最新バージョンではありません。このため、既知のバグの修正の一部が未適用となっています。これにより接続の問題が発生する可能性があります。"
   },
   "chromeosversiontest_problem_title": {
      "description": "Title for when a problem is found with the ChromeOS version.",
      "message": "Chrome OS は最新ではありません"
   },
   "chromeosversiontest_problem_version": {
      "description": "Logger record for ChromeOS platform number for which we render a problem verdict.",
      "message": "Chrome OS のプラットフォーム番号のしきい値（下回ったとき、問題ありという結果を表示）:"
   },
   "chromeosversiontest_raw_useragent": {
      "description": "Raw browser user-agent",
      "message": "未処理のブラウザ ユーザー エージェント: "
   },
   "chromeosversiontest_short_platform": {
      "description": "Short ChromeOS platform number parsed from the HTTP user-agent string",
      "message": "Chrome OS のプラットフォーム番号（短縮）: "
   },
   "chromeversiontest_full_browser": {
      "description": "Short browser version number",
      "message": "ブラウザのバージョン番号（完全）: "
   },
   "chromeversiontest_name": {
      "description": "Name for the Chrome Version test",
      "message": "Chrome のバージョン テスト"
   },
   "chromeversiontest_no_problem_version": {
      "description": "Logger record for Chrome version test for which we render a no problem verdict.",
      "message": "Chrome のバージョン番号のしきい値（等しいか上回ったとき、問題なしという結果を表示）: "
   },
   "chromeversiontest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the Chrome version.",
      "message": "ご使用の Google Chrome は最新バージョンです。接続に関する既知のバグはすべて修正されています。"
   },
   "chromeversiontest_noproblem_title": {
      "description": "Title for when no problem is found with the Chrome version.",
      "message": "Google Chrome は最新バージョンです"
   },
   "chromeversiontest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the Chrome version.",
      "message": "ご使用の Google Chrome は最新バージョンではありません。このため、既知のバグの修正の一部が未適用となっています。これにより接続の問題が発生する可能性があります。"
   },
   "chromeversiontest_problem_title": {
      "description": "Title for when a problem is found with the Chrome version.",
      "message": "Google Chrome は最新バージョンではありません"
   },
   "chromeversiontest_problem_version": {
      "description": "Logger record for Chrome version test for which we render a no problem verdict.",
      "message": "Chrome のバージョン番号のしきい値（下回ったとき、問題ありという結果を表示）: "
   },
   "chromeversiontest_raw_useragent": {
      "description": "Raw browser user-agent",
      "message": "未処理のブラウザ ユーザー エージェント: "
   },
   "chromeversiontest_short_browser": {
      "description": "Short browser version number",
      "message": "ブラウザのバージョン番号（短縮）: "
   },
   "dnspoisoningtest_beginning_resolution": {
      "description": "Logger record for noting a new DNS resolution attempt.",
      "message": "テスト #/テストするホスト名: "
   },
   "dnspoisoningtest_log_address_returned": {
      "description": "Logger record for DNS response address.",
      "message": "解決済み DNS アドレスが返されました: "
   },
   "dnspoisoningtest_log_statuscode_returned": {
      "description": "Logger record for DNS response status code.",
      "message": "テストで次のステータス コードが返されました: "
   },
   "dnspoisoningtest_name": {
      "description": "Name for DNS poisoning test.",
      "message": "DNS 汚染テスト"
   },
   "dnspoisoningtest_no_addr_returned": {
      "description": "Logger record for when DNS resolution returns no address field.",
      "message": "テストで DNS アドレスのフィールドが返されませんでした（null に設定されています）"
   },
   "dnspoisoningtest_no_problem_threshold": {
      "description": "Log record for the threshold of no problem",
      "message": "想定どおりの IP アドレスがリゾルバから返された場合、DNS の結果は汚染されていないと考えられます。"
   },
   "dnspoisoningtest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the DNS poisoning test.",
      "message": "DNS から想定どおりの結果が返されました。汚染されている可能性は低いと考えられます。"
   },
   "dnspoisoningtest_noproblem_title": {
      "description": "Title for when no problem is found with the DNS poisoning test.",
      "message": "DNS サーバーから想定どおりの結果が返されました"
   },
   "dnspoisoningtest_noresult_code_returned": {
      "description": "Logger record for when DNS resolution returns no result status code field.",
      "message": "テスト。結果のステータス コードがありません。テストに失敗したためテストを中止します。"
   },
   "dnspoisoningtest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the DNS poisoning test.",
      "message": "DNS レスポンスの汚染が検出されました。DNS レスポンスが汚染されていると、リクエストしたネットワーク ホスト以外の場所に通信が誘導されます。"
   },
   "dnspoisoningtest_problem_threshold": {
      "description": "Log record for the threshold of a problem",
      "message": "想定した IP アドレスがリゾルバから返されなかった場合、DNS の結果は汚染されていると考えられます。"
   },
   "dnspoisoningtest_problem_title": {
      "description": "Title for when a problem is found with the DNS poisoning test.",
      "message": "DNS から想定外の結果が返されました。汚染されている可能性があります"
   },
   "hangoutsblockedtest_log_tcp_connection_failure": {
      "description": "Log record for when a TCP connection appears to be blocked on port 443 to a required host",
      "message": "ポート 443 で TCP 接続がブロックされているため、接続に失敗しました。ホスト: "
   },
   "hangoutsblockedtest_log_tcp_connection_success": {
      "description": "Log record for when a TCP connection succeeds on port 443 to a required host",
      "message": "ポート 443 で TCP 接続に成功しました。ホスト: "
   },
   "hangoutsblockedtest_log_udp_connection_failure": {
      "description": "Log record for when a UDP connection appears to be blocked",
      "message": "宛先ポートで UDP 接続がブロックされているため、接続に失敗しました。ポート: "
   },
   "hangoutsblockedtest_log_udp_connection_success": {
      "description": "Log record for when a UDP connection can successfully send and receive data",
      "message": "宛先ポートで UDP 接続に成功しました。ポート: "
   },
   "hangoutsblockedtest_name": {
      "description": "Name for the Hangouts blocked test",
      "message": "ハングアウト接続テスト"
   },
   "hangoutsblockedtest_no_problem_criteria": {
      "description": "Criteria under which the Hangouts blocked test returns a no problem verdict",
      "message": "次の場合はハングアウト接続テストで問題なしという結果が返されます: （1）19302～19309 のいずれかの UDP ポートで stun.l.google.com への接続を確立できる場合 （2）apis.google.com、clients6.google.com、plus.google.com、talkgadget.google.com への TCP 接続を確立できる場合"
   },
   "hangoutsblockedtest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found in the Hangouts blocked test",
      "message": "ハングアウト サービスへの接続で問題は見つかりませんでした。"
   },
   "hangoutsblockedtest_noproblem_title": {
      "description": "Title for when no problem is found in the Hangouts blocked test",
      "message": "ハングアウトに接続できます"
   },
   "hangoutsblockedtest_potentialproblem_subtitle_udp_media_blocked": {
      "description": "Subtitle for when a potential problem is found from the Hangouts blocked test whereby UDP is blocked to Hangouts media host.",
      "message": "UDP ポート 19302～19309 でハングアウト メディア サービスに接続できません。"
   },
   "hangoutsblockedtest_potentialproblem_title": {
      "description": "Title for when a potential problem is found in the Hangouts blocked test",
      "message": "ハングアウトへの接続速度が一時的に低下しているようです"
   },
   "hangoutsblockedtest_problem_criteria": {
      "description": "Criteria under which the Hangouts blocked test returns a problem verdict",
      "message": "次の場合はハングアウト接続テストで問題ありという結果が返されます: （1）19302～19309 のすべての UDP 宛先ポートで stun.l.google.com への接続がブロックされている場合 （2）ポート 443 で apis.google.com、clients6.google.com、plus.google.com、talkgadget.google.com のいずれかのホストへの TCP 接続に失敗した場合"
   },
   "hangoutsblockedtest_problem_subtitle": {
      "description": "Subtitle for when a problem is found from the Hangouts blocked test",
      "message": "ハングアウトへの接続に必要なポートとホストがブロックされているようです。"
   },
   "hangoutsblockedtest_problem_subtitle_tcp_chat_blocked": {
      "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP is blocked to Hangouts chat hosts.",
      "message": "ハングアウト チャット サービスに接続できません。"
   },
   "hangoutsblockedtest_problem_subtitle_tcp_media_tcp_chat_blocked": {
      "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP is blocked to Hangouts chat hosts.",
      "message": "TCP ポート 443 でハングアウト チャット サービスとハングアウト メディア サービスに接続できません。"
   },
   "hangoutsblockedtest_problem_subtitle_udp_media_tcp_media_blocked": {
      "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP and UDP is blocked to Hangouts media host.",
      "message": "TCP ポート 443 と UDP ポート 19302～19309 でハングアウト メディア サービスに接続できません。"
   },
   "hangoutsblockedtest_problem_title": {
      "description": "Title for when a problem is found from the Hangouts blocked test",
      "message": "ハングアウトへの接続を確立できませんでした"
   },
   "httplatencytest_log_average_time": {
      "description": "Logger record for when TCP connection breaks an HTTP request",
      "message": "HTTP レスポンスの平均時間（ミリ秒）: "
   },
   "httplatencytest_log_network_error": {
      "description": "Logger record for when TCP connection breaks an HTTP request",
      "message": "エラーが発生しました。リクエスト #/エラーのステータス: "
   },
   "httplatencytest_log_num_requests": {
      "description": "Logger record for the total number of HTTP requests",
      "message": "HTTP リクエストの合計数: "
   },
   "httplatencytest_log_response_details": {
      "description": "Logger record for the details of a specific response",
      "message": "HTTP レスポンス #/受信時刻（マイクロ秒単位のタイムスタンプ）/経過時間（ミリ秒）: "
   },
   "httplatencytest_log_response_time": {
      "description": "Logger record for the total HTTP response time",
      "message": "HTTP レスポンスの合計時間（ミリ秒）: "
   },
   "httplatencytest_name": {
      "description": "Name for the HTTP latency test",
      "message": "Google ウェブサイト HTTP 待ち時間テスト"
   },
   "httplatencytest_no_problem_time": {
      "description": "Logger record for http latency time for which we render a no problem verdict.",
      "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（下回ったとき、問題なしという結果を表示）: "
   },
   "httplatencytest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found in the HTTP latency test",
      "message": "Google へのウェブ リクエストは速やかに受信されています。"
   },
   "httplatencytest_noproblem_title": {
      "description": "Title for when no problem is found in the HTTP latency test",
      "message": "Google 関連サイトからのレスポンスの受信で遅延は発生していません"
   },
   "httplatencytest_potential_problem_time": {
      "description": "Logger record for http latency time for which we render a potential problem verdict.",
      "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（範囲内のとき、問題の可能性ありという結果を表示）: "
   },
   "httplatencytest_potentialproblem_subtitle": {
      "description": "Subtitle for when a potential problem is found in the HTTP latency test",
      "message": "Google 関連サイトからのレスポンスの受信に想定より少し時間がかかっています。ネットワーク遅延の可能性があります。"
   },
   "httplatencytest_potentialproblem_title": {
      "description": "Title for when a potential problem is found in the HTTP latency test",
      "message": "Google へのウェブ リクエストに予想より時間がかかっています"
   },
   "httplatencytest_problem_subtitle": {
      "description": "Subtitle for when a problem is found in the HTTP latency test",
      "message": "Google 関連サイトからのレスポンス受信に想定より時間がかかっています。ネットワーク遅延の可能性があります。"
   },
   "httplatencytest_problem_time": {
      "description": "Logger record for http latency time for which we render a problem verdict.",
      "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（上回ったとき、問題ありという結果を表示）: "
   },
   "httplatencytest_problem_title": {
      "description": "Title for when a problem is found in the HTTP latency test",
      "message": "Google へのウェブ リクエストに時間がかかりすぎています"
   },
   "passing_test_title": {
      "description": "Page section title for test that passed",
      "message": "合格したテスト"
   },
   "passing_tests_title": {
      "description": "Page section title for tests that passed",
      "message": "合格したテスト"
   },
   "pinggatewaytest_log_failure": {
      "description": "Logger record for when there is no response to an ICMP packet",
      "message": "ゲートウェイの IP に直接送信された ICMP クエリで応答パケットを受信しませんでした。"
   },
   "pinggatewaytest_log_gateway_known": {
      "description": "Logger record for the gateway of the IP",
      "message": "ゲートウェイの IP を特定しました: "
   },
   "pinggatewaytest_log_gateway_unknown": {
      "description": "Logger record for when the gateway of the IP could not be determined",
      "message": "ゲートウェイの IP を特定できませんでした"
   },
   "pinggatewaytest_log_latency": {
      "description": "Logger record for the latency of an ICMP packet in the ping gateway test",
      "message": "ICMP パケットの待ち時間（ミリ秒）: "
   },
   "pinggatewaytest_log_same_ip_response": {
      "description": "Logger record for when the IP that is pinged returns the terminal destination IP and not the gateway IP",
      "message": "TTL を 1 に設定しているリモート ホストへの ICMP パケット送信で、次のリモート ホストの IP と同じ IP が返されました: "
   },
   "pinggatewaytest_name": {
      "description": "Name for the ping gateway test",
      "message": "ping ゲートウェイ テスト"
   },
   "pinggatewaytest_no_problem_time": {
      "description": "Logger record for the gateway latency below which we render a no problem verdict.",
      "message": "ゲートウェイを ping するのにかかった時間（ミリ秒）のしきい値（下回ったとき、問題なしという結果を表示）: "
   },
   "pinggatewaytest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found in the ping gateway test",
      "message": "ゲートウェイを ping して迅速な応答が返されました。"
   },
   "pinggatewaytest_noproblem_title": {
      "description": "Title for when no problem is found in the ping gateway test",
      "message": "ゲートウェイにアクセス可能"
   },
   "pinggatewaytest_problem_subtitle": {
      "description": "Subtitle for when a problem is found in the ping gateway test",
      "message": "ゲートウェイを ping しても迅速な応答が返されません。"
   },
   "pinggatewaytest_problem_time": {
      "description": "Logger record for the gateway latency above which we render a problem verdict.",
      "message": "ゲートウェイを ping するのにかかった時間（ミリ秒）のしきい値（上回ったとき、問題ありという結果を表示）: "
   },
   "pinggatewaytest_problem_title": {
      "description": "Title for when a problem is found in the ping gateway test",
      "message": "ゲートウェイにアクセス不能"
   },
   "resolverlatencytest_average_resolution_time": {
      "description": "Logger record for noting the average DNS resolution time.",
      "message": "DNS 解決にかかった平均時間（ミリ秒）: "
   },
   "resolverlatencytest_beginning_resolution": {
      "description": "Logger record for noting that DNS resolution is beginning.",
      "message": "ホスト名の解決を試行します。#: "
   },
   "resolverlatencytest_name": {
      "description": "Name for the Resolver Latency test",
      "message": "リゾルバ待ち時間テスト"
   },
   "resolverlatencytest_no_problem_time": {
      "description": "Logger record for dns resolution time for which we render a no problem verdict.",
      "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（下回ったとき、問題なしという結果を表示）: "
   },
   "resolverlatencytest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the DNS Latency test.",
      "message": "DNS サーバーはホスト名（例: google.com）を IP アドレス（例: 74.125.228.98）に変換します。ブラウザでインターネットに接続するには、このプロセスが必要です。Chrome では、ローカルのリゾルバを使って DNS リクエストを直ちに変換できます。これによりページの読み込みが高速化されます。"
   },
   "resolverlatencytest_noproblem_title": {
      "description": "Title for when no problem is found with the DNS Latency test.",
      "message": "DNS 解決で遅延は発生していません"
   },
   "resolverlatencytest_potential_problem_subtitle": {
      "description": "Subtitle for when a potential problem is found with the DNS Latency test.",
      "message": "DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換します。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。この変換を行う DNS サーバーで時間がかかりすぎているため、インターネット接続に遅延が発生しています。"
   },
   "resolverlatencytest_potential_problem_time": {
      "description": "Logger record for dns resolution time for which we render a potential problem verdict.",
      "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（範囲内のとき、問題の可能性ありという結果を表示）: "
   },
   "resolverlatencytest_potentialproblem_title": {
      "description": "Title for when a potential problem is found with the DNS Latency test.",
      "message": "DNS 解決に平均以上の時間がかかっています"
   },
   "resolverlatencytest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the DNS Latency test.",
      "message": "DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換します。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。この変換を行う DNS サーバーで時間がかかりすぎているため、インターネット接続に遅延が発生しています。"
   },
   "resolverlatencytest_problem_time": {
      "description": "Logger record for dns resolution time for which we render a problem verdict.",
      "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（上回ったとき、問題ありという結果を表示）: "
   },
   "resolverlatencytest_problem_title": {
      "description": "Title for when a problem is found with the DNS Latency test.",
      "message": "DNS 解決に時間がかかりすぎています"
   },
   "resolverlatencytest_queryresult_received": {
      "description": "Logger record for noting that DNS resolution is beginning.",
      "message": "DNS 解決の結果を受信しました。テスト番号/現在の時刻/所要時間（ミリ秒）/開始時刻（ミリ秒）: "
   },
   "resolverlatencytest_total_hosts_resolved": {
      "description": "Logger record for noting the total hosts resolved.",
      "message": "解決された DNS ホストの合計数: "
   },
   "resolverlatencytest_total_resolution_time": {
      "description": "Logger record for noting the total DNS resolution time.",
      "message": "すべてのテストで DNS 解決にかかった合計時間（ミリ秒）: "
   },
   "resolverpresenttest_criteria_failure": {
      "description": "Logger record denoting the failed DNS query status code result",
      "message": "DNS リゾルバ テストは、単独の DNS クエリを実行し、有効なレスポンスが返されなかった場合は問題ありという結果を返します。"
   },
   "resolverpresenttest_criteria_success": {
      "description": "Logger record denoting the successful DNS query status code result",
      "message": "DNS リゾルバ テストは、単独の DNS クエリを実行し、有効なレスポンスが返された場合は問題なしという結果を返します。"
   },
   "resolverpresenttest_gettinghostname": {
      "description": "Logger record denoting that the resolverpresenttest is about to resolve a hostname",
      "message": "ホスト名の解決を試行します: "
   },
   "resolverpresenttest_hostnameresult": {
      "description": "Logger record denoting the IP result that the DNS resolved the hostname to",
      "message": "ホスト名が次の IP アドレスに変換されました: "
   },
   "resolverpresenttest_log_statuscodefailure": {
      "description": "Logger record denoting the failed DNS query status code result",
      "message": "DNS サーバーから問題を示すステータス コードが返されました: "
   },
   "resolverpresenttest_log_statuscodesuccess": {
      "description": "Logger record denoting the successful DNS query status code result",
      "message": "DNS サーバーから成功のステータス コードが返されました: "
   },
   "resolverpresenttest_name": {
      "description": "Name for the Resolver Present test",
      "message": "リゾルバ応答テスト"
   },
   "resolverpresenttest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the DNS Resolver Present test.",
      "message": "ホスト名（例: www.google.com）を IP アドレスに正常に変換した DNS サーバーが Chrome で検出されました。"
   },
   "resolverpresenttest_noproblem_title": {
      "description": "Title for when no problem is found with the DNS Resolver Present test.",
      "message": "DNS サーバーを使用できます"
   },
   "resolverpresenttest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the DNS Resolver Present test.",
      "message": "DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換します。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。DNS サーバーが動作していないため、アクセスしようとしているウェブサイトの IP アドレスを Chrome で特定できません。ISP またはネットワーク管理者までお問い合わせください。"
   },
   "resolverpresenttest_problem_title": {
      "description": "Title for when a problem is found with the DNS Resolver Present test.",
      "message": "使用できる（機能する）DNS サーバーがありません"
   },
   "resolverpresenttest_testcompleted": {
      "description": "Logger record denoting that the resolverpresenttest is complete",
      "message": "DNS サーバーから DNS クエリの結果が返されました。"
   },
   "resolverpresenttest_testfailed": {
      "description": "Logger record denoting that the resolverpresenttest failed as the resolver did not return any result (even an error)",
      "message": "DNS サーバーからオブジェクトが返されず、レコードの DNS エントリもなかったため、テストは完了しませんでした。"
   },
   "result_no_connectivity_problems": {
      "description": "Tests did not find a problem",
      "message": "ネットワーク接続は正常に動作しているようです。"
   },
   "setting_about": {
      "description": "The setting that lets the user learn about the app",
      "message": "情報"
   },
   "setting_hide_passing_test": {
      "description": "The setting that toggles whether to show passing tests",
      "message": "合格したテストを非表示にする"
   },
   "setting_rerun_tests": {
      "description": "The setting that allows a user to re-runs tests",
      "message": "テストを再実行"
   },
   "setting_send_feedback": {
      "description": "The setting that prompts the user to send feedback",
      "message": "フィードバックを送信..."
   },
   "setting_show_passing_test": {
      "description": "The setting that toggles whether to show passing tests",
      "message": "合格したテストを表示する"
   },
   "tcpfirewalltest_log_analysis_summary": {
      "description": "Logger record for summarizing the analysis of the various TCP connections made in a test",
      "message": "ファイアウォール テストの結果: 実行されたテスト/確認されたポート/接続に失敗した数: "
   },
   "tcpfirewalltest_log_connection_about_begun": {
      "description": "Logger record for when a TCP connection to a specific host and port is about to begin",
      "message": "TCP 接続を試行します。#/ホスト名/ポート: "
   },
   "tcpfirewalltest_log_connection_status_known": {
      "description": "Logger record for when a TCP connection status code is known",
      "message": "TCP ファイアウォールのテストで次の TCP のステータス コードが返されました: "
   },
   "tcpfirewalltest_log_count_failed_attempt": {
      "description": "Logger record for denoting failure of a TCP connection",
      "message": "接続テスト試行に失敗しました。Chrome ネットワーク スタックから TCP の成功のステータス コードは返されませんでした。代わりに次のステータス コードが返されました: "
   },
   "tcpfirewalltest_log_dns_broken": {
      "description": "Logger record for when TCP connections seem to fail due to DNS resolver not working",
      "message": "検出された DNS リゾルバは使用できません。このため、ファイアウォールが存在するかどうかを判定できません"
   },
   "tcpfirewalltest_log_network_disconnected": {
      "description": "Logger record for when TCP connections seem to reveal that the network is unavailable",
      "message": "検出されたネットワークは使用できません。このため、ファイアウォールが存在するかどうかを判定できません"
   },
   "tcpfirewalltest_name": {
      "description": "Name for TCP Firewall test",
      "message": "TCP ファイアウォール テスト"
   },
   "tcpfirewalltest_no_problem_threshold": {
      "description": "Logger record for TCP firewall test for which we render a no problem verdict.",
      "message": "TCP 接続テストの結果で失敗の割合が次と同じか下回ったとき、問題なしと表示されます: "
   },
   "tcpfirewalltest_noproblem_subtitle": {
      "description": "Subtitle for when no problem is found with the TCP Firewall test.",
      "message": "次のポートでインターネット接続に関する制限は検出されませんでした: "
   },
   "tcpfirewalltest_noproblem_title": {
      "description": "Title for when no problem is found with the TCP Firewall test.",
      "message": "次のポートでは、インターネット トラフィックはファイアウォールによってブロックされていません: "
   },
   "tcpfirewalltest_potential_problem_threshold": {
      "description": "Logger record for TCP firewall test for which we render a potential problem verdict.",
      "message": "TCP 接続テストの結果で失敗の割合が次の範囲内にあるとき、問題の可能性ありと表示されます: "
   },
   "tcpfirewalltest_potentialproblem_subtitle": {
      "description": "Subtitle for when a potential problem is found with the TCP Firewall test.",
      "message": "ネットワークで、よく使用されるインターネット接続に対し制限がかけられているようです。"
   },
   "tcpfirewalltest_potentialproblem_title": {
      "description": "Title for when a potential problem is found with the TCP Firewall test.",
      "message": "次のポートで、インターネット トラフィックがファイアウォールによってブロックされている可能性があります: "
   },
   "tcpfirewalltest_problem_subtitle": {
      "description": "Subtitle for when a problem is found with the TCP Firewall test.",
      "message": "ネットワークで、よく使用されるインターネット接続に対し制限がかけられています。"
   },
   "tcpfirewalltest_problem_threshold": {
      "description": "Logger record for TCP firewall test for which we render a problem verdict.",
      "message": "TCP 接続テストの結果で失敗の割合が次と同じとき、問題ありと表示されます: "
   },
   "tcpfirewalltest_problem_title": {
      "description": "Title for when a problem is found with the TCP Firewall test.",
      "message": "次のポートで、インターネット トラフィックがファイアウォールによってブロックされています: "
   },
   "telnet_log_connection_established": {
      "description": "Log connection established",
      "message": "TCP 接続を確立しました。ホスト/ポート/ステータス コード: "
   },
   "telnet_log_connection_established_successfully": {
      "description": "Log TCP connection established successfully",
      "message": "TCP 接続を正常に確立しました。ホスト/ポート: "
   },
   "telnet_log_connection_failure": {
      "description": "Log TCP connection failure",
      "message": "TCP 接続に失敗しました。ホスト/ポート/ステータス コード: "
   },
   "telnet_log_connection_failure_refused": {
      "description": "Log TCP connection failure due to refusal",
      "message": "接続エラー。理由: 接続拒否"
   },
   "telnet_log_connection_failure_timeout": {
      "description": "Log TCP connection failure due to timeout",
      "message": "接続エラー。理由: タイムアウト"
   },
   "telnet_log_connection_failure_unknown": {
      "description": "Log TCP connection failure reason unknown",
      "message": "接続エラー。理由: 不明"
   },
   "telnet_log_error_reading_tcp_data": {
      "description": "Log error reading TCP data",
      "message": "TCP データの読み取り中にエラーが発生しました。エラー コード: "
   },
   "telnet_log_parsed_response_size": {
      "description": "Log received TCP size",
      "message": "TCP ソケットからデータを正常に読み取りました。サイズ（バイト）: "
   },
   "telnet_log_parsed_tcp_response": {
      "description": "Log data from TCP socket",
      "message": "TCP ソケットから未処理のデータを受信しました: "
   },
   "telnet_log_preparing_to_send_data": {
      "description": "Log preparing to send TCP data",
      "message": "データの送信を準備しています。サイズ（バイト）: "
   },
   "telnet_log_socket_created": {
      "description": "Log TCP socket created",
      "message": "TCP ソケットを作成しています。番号/ホスト/ポート: "
   },
   "telnet_log_successfully_sent_data": {
      "description": "Log successfully sent TCP data",
      "message": "データを正常に送信しました。サイズ（バイト）: "
   },
   "telnet_log_tcp_timeout_setting": {
      "description": "Log TCP timeout setting",
      "message": "TCP のタイムアウトを設定しています。長さ（ミリ秒）: "
   },
   "test_result_copy_logs": {
      "description": "Link to copy result logs",
      "message": "結果のログをコピー"
   },
   "test_result_hide_logs": {
      "description": "Link to hide logs",
      "message": "ログを非表示にする..."
   },
   "test_result_issue_found": {
      "description": "Show a header for when an issue was found",
      "message": "問題が見つかりました"
   },
   "test_result_issues_found": {
      "description": "Show a header for when issues were found",
      "message": "複数の問題が見つかりました"
   },
   "test_result_log_criteria": {
      "description": "Show a header in the logs for the criteria section",
      "message": "条件"
   },
   "test_result_log_details": {
      "description": "Show a header in the logs for the details section",
      "message": "詳細"
   },
   "test_result_log_summary": {
      "description": "Show header in the logs for the summary section",
      "message": "概要"
   },
   "test_result_log_support_details": {
      "description": "Show a header in the logs for the support details section",
      "message": "サポートの詳細"
   },
   "test_result_log_test_id": {
      "description": "In the logs for a test, print out the test ID",
      "message": "テスト ID: "
   },
   "test_result_log_test_name": {
      "description": "In the logs for a test, print out the test name",
      "message": "テスト名: "
   },
   "test_result_log_test_verdict": {
      "description": "In the logs for a test, print out the test verdict",
      "message": "テストの結果: "
   },
   "test_result_log_verdict_no_problem": {
      "description": "In the logs for a test, print out the test verdict",
      "message": "問題は検出されませんでした"
   },
   "test_result_log_verdict_potential_problem": {
      "description": "In the logs for a test, print out the test verdict",
      "message": "潜在的な問題が検出されました"
   },
   "test_result_log_verdict_problem": {
      "description": "In the logs for a test, print out the test verdict",
      "message": "問題が検出されました"
   },
   "test_result_show_logs": {
      "description": "Link to show logs",
      "message": "ログを表示する..."
   },
   "tests_failed_message": {
      "description": "Test to display to inform the user that the tests failed",
      "message": "接続診断テストの実行中にエラーが発生しました。テストは中止されました。この問題が解消されない場合は、[設定] メニューの [フィードバックを送信...] オプションをクリックしてください。"
   },
   "tests_running_message": {
      "description": "Text to inform the user the tests are running.",
      "message": "テストを実行しています。これには数分かかる場合があります..."
   },
   "udpsocket_log_error_reading_udp_data": {
      "description": "Log error reading UDP data",
      "message": "UDP データの読み取り中にエラーが発生しました。エラー コード: "
   },
   "udpsocket_log_parsed_response_size": {
      "description": "Log received UDP packet size",
      "message": "UDP ソケットからデータを正常に読み取りました。サイズ（バイト）: "
   },
   "udpsocket_log_parsed_udp_response": {
      "description": "Log data from UDP socket",
      "message": "UDP ソケットから未処理のデータを受信しました: "
   },
   "udpsocket_log_preparing_to_send_data": {
      "description": "Log preparing to send UDP data",
      "message": "UDP ソケット データの送信を準備しています。サイズ（バイト）: "
   },
   "udpsocket_log_socket_created": {
      "description": "Log UDP socket created",
      "message": "UDP ソケットを作成しています。番号/ホスト/ポート: "
   },
   "udpsocket_log_successfully_sent_data": {
      "description": "Log successfully sent UDP data",
      "message": "データを正常に送信しました。サイズ（バイト）: "
   },
   "udpsocket_log_udp_timeout_setting": {
      "description": "Log UDP timeout setting",
      "message": "UDP のタイムアウトを設定しています。長さ（ミリ秒）: "
   },
   "warning_test_title": {
      "description": "Page section title for test that gave warning",
      "message": "警告"
   },
   "warning_tests_title": {
      "description": "Page section title for tests that gave warnings",
      "message": "警告"
   }
}
